

import { GoogleGenAI, Modality, Content } from "@google/genai";
import type { Page, GroundingChunk } from '../types';

const envApiKey = (() => {
    // Prefer the Vite-style environment variable, but keep backwards compatibility
    const metaEnv = (typeof import.meta !== "undefined" ? import.meta.env : undefined) as
        | Record<string, string | undefined>
        | undefined;

    const viteKey = metaEnv?.VITE_GEMINI_API_KEY ?? metaEnv?.GEMINI_API_KEY;
    if (viteKey) {
        return viteKey;
    }

    if (typeof process !== "undefined" && process.env) {
        return process.env.GEMINI_API_KEY ?? process.env.API_KEY;
    }

    return undefined;
})();

let aiClient: GoogleGenAI | null = envApiKey ? new GoogleGenAI({ apiKey: envApiKey }) : null;

const ensureClient = (): GoogleGenAI => {
    if (!aiClient) {
        throw new Error('Configura la variable de entorno GEMINI_API_KEY en tu archivo .env.local para habilitar las funciones de IA.');
    }
    return aiClient;
};

const FULL_BOOK: Page[] = [
  { page: 1, chapter: "A VECES CAER, A VECES VOLAR", content: "CRISTOFER BRAÑAS" },
  { page: 2, chapter: "Volver a casa", content: "Hubo un momento, no muy claro en el calendario, pero sí definitivo en el alma, en que sentí la necesidad de estar solo. No una soledad forzada ni producto de la tristeza, sino una decisión consciente, casi ritual. Apagué el teléfono, cerré la puerta con doble vuelta, y me senté frente a mí mismo como quien se encuentra con un viejo amigo después de años de ausencia.\n\nAl principio fue incómodo. El silencio tenía el volumen alto. Mis pensamientos corrían como autos sin frenos en una avenida mental congestionada. Me costaba simplemente estar. Sentir sin reaccionar, pensar sin distraerme.\n\nMe di cuenta de cuántas veces había evitado ese encuentro. Cuántas veces me escondí detrás del ruido, de las pantallas, de los otros. Pero lentamente, algo cambió.\n\nEn ese espacio íntimo y sin adornos, empecé a preguntarme cosas simples y olvidadas: ¿qué me gusta de verdad? ¿Qué cosas hago por impulso propio y cuáles por inercia? ¿Quién sería yo si nadie me estuviera mirando? Preguntas que no necesitan respuesta inmediata, pero que se instalan como semillas.\n\nEse día entendí que pasar tiempo conmigo no era una pérdida. Era una inversión. Un volver a casa.\n\nY no se trataba de encontrar una gran verdad, ni de iluminarme como un gurú en la cima de una montaña. Era mucho más simple y profundo: se trataba de aprender a estar conmigo sin querer escapar.\n\nDesde entonces, cada tanto, me regalo ese espacio. A veces en una plaza, a veces en mi cuarto, otras en el ruido mismo del mundo, pero conmigo. Porque aprendí que, si no me conozco, si no me escucho, corro el riesgo de vivir una vida ajena, diseñada por expectativas ajenas, sostenida por rutinas que no me representan.\n\nY si hay algo que merezco, al menos una vez en esta vida, es vivir una vida que se parezca a mí." },
  { page: 3, chapter: "El disfraz de la risa", content: "Aprendí a reír cuando más me dolía.\n\nFue mi mejor disfraz.\n\nLa gente ama a los que ríen, no a los que sangran.\n\nAsí que me volví un payaso de mi propia tristeza.\n\nHacía chistes mientras me ahogaba, aplaudía mientras me partía, bailaba con la soga en el cuello.\n\nY funcionó.\n\nTodos pensaban que yo era feliz.\n\nQue la vida no me pesaba, que mis pasos eran firmes, que mi alma tenía alas.\n\nPero por dentro tenía charcos, tormentas, abismos.\n\nY a veces me sentaba solo, frente al espejo, a preguntarme quién era el que sonreía en mi lugar.\n\nHasta que una noche, harto de esconderme, lloré hasta quedarme dormido.\n\nY al despertar, la risa volvió.\n\nPero esta vez, era mía. Un poco rota, sí." },
  { page: 4, chapter: "El culto a la prisa", content: "No recuerdo exactamente cuándo empezó, pero un día noté que ya no caminaba: me desplazaba como si siempre llegara tarde. Todo era urgente. Incluso lo que no importaba.\n\nDesayunaba de pie, chequeaba el celular antes de abrir los ojos, escuchaba audios en velocidad 2x. Respondía mensajes mientras cruzaba la calle, planeaba el almuerzo mientras desayunaba, pensaba en el domingo mientras vivía el martes. Mi cuerpo estaba presente, pero mi mente corría una maratón sin meta.\n\nY entonces un día, sin buscarlo, el cuerpo me dijo basta. No fue un colapso dramático ni una epifanía. Fue más sutil: una especie de vacío que no dolía, pero pesaba. Me detuve. Me senté en un banco cualquiera, en una calle cualquiera, y por primera vez en mucho tiempo... no hice nada.\n\nEl silencio no fue amable al principio. Me miró con cara de desconocido. El tiempo sin tareas se sintió como una falta de productividad, como si no mereciera existir si no estaba haciendo algo “útil”." },
  { page: 5, chapter: "El culto a la prisa", content: "Pero en ese espacio —incómodo al inicio— empecé a ver con claridad: la prisa no me estaba llevando a ningún lado. Solo me alejaba de mí. La urgencia no era más que una distracción elegante. Una excusa que me impedía sentir, pensar, o simplemente estar.\n\nEntonces entendí que el mundo no se detendría si yo lo hacía. Que vivir más lento no era rendirse, sino recuperar la soberanía sobre mi tiempo. Empecé a caminar sin auriculares. A comer sentado. A dejar mensajes sin responder de inmediato. A veces, incluso, a apagar el celular sin culpa.\n\nNo soy un experto en calma. Aún me gana la ansiedad muchas veces. Pero cada vez que puedo, me regalo un momento sin velocidad. Porque aprendí que el valor de una vida no está en cuánto hacemos, sino en cuán conscientes estamos de lo que vivimos." },
  { page: 6, chapter: "Dormir no es lo mismo que descansar", content: "Hay noches en las que el cuerpo se rinde, pero la mente no. Apago la luz, acomodo la almohada, cierro los ojos... y empieza otra jornada, más sutil y más cruel: la del pensamiento desordenado, esa procesión nocturna de ideas que no piden permiso para entrar.\n\nMe acuesto con el deseo de descansar, pero en lugar de sueños, llegan preguntas sin respuesta, escenas que se repiten, miedos sin forma, listas de tareas futuras, conversaciones pasadas. Todo junto. Todo al mismo tiempo. Como si mi cabeza creyera que el silencio exterior es una invitación para hacer más ruido adentro.\n\nHe aprendido que muchas veces el insomnio no tiene que ver con el colchón ni con la cafeína. Tiene que ver con la carga invisible que arrastro. Con lo que no dije, lo que no resolví, lo que no quiero sentir. Descansar no es solo cerrar los ojos: es permitirme soltar el peso.\n\nSoltar la necesidad de entender todo. Soltar el perfeccionismo que no me deja equivocarme en paz. Soltar la ansiedad por lo que aún no llega y la culpa por lo que ya pasó.\n\nEsa noche, en vez de luchar contra mis pensamientos, decidí observarlos. Como quien mira un río correr, sin intentar detener el agua. Me dije: \"No necesito resolverlo todo ahora. Solo necesito estar aquí, respirando.\"\n\nY eso fue descanso. No un descanso pleno, pero sí un descanso honesto. Un espacio donde, aunque el sueño no llegara de inmediato, al menos yo dejaba de pelear conmigo.\n\nDesde entonces, entendí algo que no quiero olvidar: no siempre puedo dormir a voluntad, pero sí puedo elegir descansar de mí. Y a veces, eso es suficiente para seguir." },
  { page: 7, chapter: "La trampa de los otros", content: "Hay días en los que mi propia vida me parece insuficiente, pero no porque lo sea, sino porque la estoy mirando desde afuera.\n\nBasta con un gesto involuntario: abrir una red social, deslizar el dedo. Y ahí están. Todos. Sonriendo, cumpliendo metas, viajando a lugares hermosos, amando con intensidad fotogénica. Todos parecen tenerlo claro. Todos parecen estar donde deberían estar.\n\nMenos yo.\n\nEn esos momentos, empiezo a sentir que algo falla en mí. Que voy tarde, que soy mediocre, que no estoy haciendo lo suficiente. Que mi tristeza es un error, que mis dudas me retrasan. La comparación se convierte en un veneno dulce: uno que consumo sin querer, pero que me intoxica igual.\n\nEmpiezo a desear cosas que no sé si quiero, solo porque otros las tienen. A despreciar logros propios porque no lucen como los de otros. A sentirme espectador de una obra en la que todos actúan de protagonistas, mientras yo ni siquiera recuerdo el guion.\n\nY entonces, en un esfuerzo por no naufragar, intento volver. Cierro la app. Apago la pantalla. Respiro. Me recuerdo que lo que vemos no es toda la historia. Que nadie muestra sus grietas con la misma facilidad con la que muestra sus luces. Que todos, en algún rincón, están lidiando con sus propias tormentas, aunque no las publiquen.\n\nMe obligo a mirar mi vida desde adentro. A preguntarme si mis metas me representan o si son reflejos ajenos. Me cuesta. A veces me duele. Pero prefiero esa incomodidad honesta a la anestesia de una comparación permanente.\n\nPorque una vida vivida para parecer, jamás se sentirá como propia." },
  { page: 8, chapter: "El miedo a moverme", content: "Sabía que tenía que cambiar.\n\nLo sentía en el cuerpo, en la respiración corta, en la irritación sin motivo, en esa tristeza difusa que se colaba incluso en los días soleados. Había señales por todas partes: el trabajo me drenaba, las conversaciones se volvían repetidas, los domingos tenían sabor a encierro.\n\nY sin embargo, no me movía.\n\nEl cambio era una puerta abierta. La veía ahí, esperándome. Pero al mismo tiempo, tenía miedo de cruzarla. Porque aunque lo que conocía ya no me hacía bien, al menos lo conocía. Era mi zona gris, pero era mía." },
  { page: 9, chapter: "El miedo a moverme", content: "Pensaba cosas como:\n\n\"¿Y si después es peor?\"\n\n\"¿Y si me arrepiento?\"\n\n\"¿Y si no soy capaz?\"\n\nY así me fui quedando. Como quien vive en una casa que se desmorona, pero no se atreve a mudarse por miedo a la intemperie.\n\nLo más curioso es que muchas veces el miedo no aparece como miedo. Se disfraza de lógica, de prudencia, de sensatez. Uno se convence de que “no es el momento\", de que \"hay que esperar un poco más\", de que \"ya va a pasar”. Pero no pasa. Y lo que no cambia por decisión, se va marchitando por omisión.\n\nUn día, sin mucha épica, empecé a moverme. No fue un salto heroico. Fue un gesto mínimo: decir en voz alta lo que estaba sintiendo. Hacer una llamada. Anotar una idea. Apagar una notificación. Dejar una respuesta sin dar. Fue eso: una suma de pequeñas acciones que rompían, muy de a poco, la inercia.\n\nEl cambio no llegó como una tormenta. Llegó como una grieta. Y por esa grieta, empezó a entrar aire nuevo.\n\nAhora sé que cambiar no siempre es hacer grandes cosas. A veces es simplemente dejar de sostener lo que ya no tiene sentido. Aceptar que el miedo a moverse también es parte del proceso. Pero no dejar que ese miedo decida por mí.\n\nNo tengo todo resuelto. Sigo dudando, sigo temblando a veces. Pero cada vez que me acerco a esa puerta abierta, siento algo distinto: no amenaza, sino posibilidad.\n\nY me digo:\n\nMoverse duele. Pero quedarse donde ya no hay vida... duele más." },
  { page: 10, chapter: "Empezar desde cero", content: "Hay una frase que siempre me incomodó: “Nunca es tarde para empezar de nuevo”.\n\nSuena bonita. Esperanzadora. Pero cuando uno está parado frente a las ruinas de lo que fue su vida —una relación que se rompió, un trabajo que ya no existe, un sueño que caducó— esa frase puede parecer una burla. Porque lo cierto es que empezar de nuevo no se siente como una oportunidad. Al principio, se siente como una derrota.\n\nY sin embargo, ¿qué otra opción queda?\n\nRecuerdo esa sensación: mirar alrededor y no reconocerme en nada. Lo que antes me sostenía ya no estaba. Y lo que venía después... no lo podía ver. Solo un terreno baldío. Una especie de silencio incómodo entre el final de algo y el inicio de no sé qué.\n\nTuve que desaprender la idea de que empezar de nuevo es arrancar con entusiasmo. Porque no lo es. Empezar de nuevo, de verdad, suele ser lento. A veces triste. Como barrer con cuidado los restos de una tormenta que aún suena en la memoria.\n\nY en ese proceso, aprendí algo importante: no se empieza desde cero. Se empieza desde lo vivido.\n\nDesde lo aprendido. Desde lo roto, sí, pero también desde lo que resistió.\n\nDesde el dolor, pero también desde la fuerza que surgió para seguir." },
  { page: 11, chapter: "Empezar desde cero", content: "Un día, sin fecha importante, me levanté y decidí hacer algo distinto. Pequeño. Ir a un lugar nuevo. Probar algo sin expectativas. Llenar una hoja en blanco con una sola palabra. No se sintió como un nuevo comienzo, pero lo era.\n\nLos inicios no siempre anuncian su llegada. A veces son tan sutiles que uno solo los reconoce tiempo después, cuando mira hacia atrás y dice: “Ahí empezó todo”.\n\nHoy no tengo todo resuelto. Pero tengo algo que antes no tenía: la certeza de que si todo se cae, puedo volver a levantarme. No igual. No como antes. Sino de otra forma, más consciente, más liviana, más mía.\n\nPorque empezar de nuevo no es un castigo. Es una posibilidad.\n\nUna página limpia que duele mirar al principio, pero que con el tiempo... se convierte en hogar." },
  { page: 12, chapter: "Amor propio en tiempos revueltos", content: "Hay momentos en los que el mundo entero parece pedir algo de mí. Rendimiento, respuestas, sonrisas, presencia.\n\nY yo doy.\n\nDoy aunque esté agotado. Doy aunque no quiera. Doy por costumbre, por miedo, por esa vieja idea de que valgo más cuando soy útil para los demás.\n\nHasta que un día, sin aviso, me apago.\n\nNo colapso de golpe, simplemente... dejo de sentirme. Me vuelvo un eco. Una versión de mí que funciona, pero no vibra." },
  { page: 13, chapter: "Amor propio en tiempos revueltos", content: "Fue en uno de esos días grises donde entendí que el amor propio no es solo autoestima, ni frases bonitas frente al espejo. Es, muchas veces, decirme que no puedo más y permitírmelo. Es cuidarme como cuidaría a alguien que amo: con compasión, con paciencia, con ternura... incluso cuando estoy insoportable.\n\nEl amor propio no siempre se ve bien. A veces es decir “no” y decepcionar. A veces es descansar mientras el mundo sigue corriendo. A veces es borrar un mensaje antes de enviarlo. A veces es reconocer que no quiero ser fuerte todo el tiempo.\n\nTambién aprendí que amarme no siempre se siente como una recompensa. A veces se siente como un trabajo. Uno silencioso, interno, que no recibe aplausos. Porque nadie celebra cuando decidís no exigirte más allá del límite. Nadie aplaude cuando elegís quedarte en silencio en lugar de responder por compromiso. Pero ahí, en esas decisiones invisibles, es donde se construye el verdadero amor propio.\n\nHay días en que no me sale. Días en los que me trato con dureza, en que me juzgo con una severidad que jamás usaría con otros. En esos días, mi único acto de amor es darme otra oportunidad mañana.\n\nY eso basta.\n\nNo necesito ser mi mejor versión todos los días.\n\nSolo necesito estar ahí para mí, incluso cuando no me gusto tanto.\n\nPorque si no soy hogar para mí, viviré siempre buscando refugios en otros. Y el amor, cuando nace desde la carencia, siempre cobra un precio.\n\nHoy, elijo practicar ese amor suave pero firme.\n\nElijo tratarme como quien está aprendiendo a vivir. Porque eso soy. Y eso basta." },
  { page: 14, chapter: "La ansiedad por el futuro", content: "Pensar en el futuro solía ser emocionante.\n\nDe chico, imaginaba todo lo que podía ser: astronauta, músico, viajero, héroe. El futuro era un lugar sin límites.\n\nPero con los años, dejó de ser promesa y se convirtió en amenaza.\n\nUna lista interminable de “tengo que”.\n\nUn reloj que corre más rápido que yo.\n\nUna voz que susurra: “Ya tendrías que haber llegado.”\n\nY entonces empecé a vivir pendiente de lo que vendrá. Haciendo planes sobre planes. Trazando rutas imaginarias. Proyectando todo... menos lo que sentía hoy. Como si pensar el futuro pudiera evitarme el fracaso. Como si anticiparlo fuera suficiente para controlarlo.\n\nPero nunca es suficiente.\n\nLa ansiedad no se calma con más planificación.\n\nPorque en el fondo, no es falta de organización: es falta de seguridad en uno mismo.\n\nEs miedo a lo que no puedo prever. A no estar a la altura. A perder el control.\n\nUn día me rendí. No a la ansiedad, sino al intento de predecirlo todo." },
  { page: 15, chapter: "La ansiedad por el futuro", content: "Y empecé a volver al presente. A hacer lo único que podía: respirar hoy, actuar hoy, elegir hoy.\n\nNo porque no importe el futuro, sino porque no lo puedo vivir todavía. Solo puedo sembrar.\n\nLa ansiedad no desaparece. Pero aprendí a no darle el timón.\n\nAhora la escucho, pero no la obedezco.\n\nY cada vez que vuelve con su presión disfrazada de urgencia, me digo:\n\n“No hace falta tener todo claro para avanzar. Solo hace falta dar el próximo paso.”" },
  { page: 16, chapter: "Perdonarme", content: "De todas las personas que herí en mi vida, yo fui una de ellas.\n\nMe exigí más de lo que podía. Me juzgué con una dureza que no usé con nadie. Me hablé mal en silencio. Me castigué por errores que ya estaban lejos, pero que seguía repitiéndome como un mantra.\n\nY no porque me odiara. Sino porque no sabía tratarme de otra forma.\n\nAprendí a castigarme antes que a consolarme.\n\nA culparme antes que a comprenderme.\n\nHasta que un día, frente al espejo —no el físico, sino el interno— me pregunté:\n\n¿Qué me hace pensar que no merezco perdón?\n\n¿De dónde saqué esa idea de que solo los demás pueden equivocarse y ser abrazados, pero yo no?\n\nFue entonces cuando entendí:\n\nPerdonarse no es justificar todo.\n\nEs reconocer el daño, sí. Pero también abrazar al que lo hizo. Al yo que no sabía más. Que estaba roto. Que actuó desde el miedo o la necesidad.\n\nPerdonarme fue empezar a hablarme distinto.\n\nFue dejar de revivir viejos errores como castigo y convertirlos en lecciones.\n\nFue mirarme con ojos de proceso, no de sentencia.\n\nHoy sigo fallando.\n\nPero cuando lo hago, me trato con más amabilidad.\n\nPorque si no me perdono, sigo arrastrando una culpa que me impide crecer.\n\nY si quiero seguir —de verdad seguir— necesito reconciliarme con quien he sido.\n\nSolo así puedo convertirme en quien estoy destinado a ser." },
  { page: 17, chapter: "La presión de ser lo que esperan", content: "No sé en qué momento exacto ocurrió.\n\nQuizás fue sutil, como todo lo importante: un gesto, una frase, una mirada de desaprobación.\n\nLo cierto es que, sin darme cuenta, empecé a vivir con una mochila invisible: las expectativas.\n\nDe la familia. De los amigos. De la sociedad.\n\nPero también, y tal vez sobre todo, las mías.\n\nO mejor dicho: las versiones de mí que imaginé que debía ser.\n\nEl exitoso. El que no se equivoca. El que está disponible para todos.\n\nY sin embargo, por dentro... agotado.\n\nHay una forma de dolor que no deja marcas visibles: la de vivir tratando de cumplir con todos, menos conmigo.\n\nDe postergar deseos por miedo a decepcionar.\n\nDe seguir un camino no porque me inspire, sino porque \"es lo que se espera de mí\".\n\nDurante mucho tiempo creí que adaptarme era madurez. Que resignar lo propio era responsabilidad.\n\nPero no lo era.\n\nEra miedo.\n\nMiedo a perder amor, reconocimiento, pertenencia.\n\nHasta que un día me pregunté:\n\n¿Y si cumplir expectativas ajenas me aleja de mi propia vida?" },
  { page: 18, chapter: "La presión de ser lo que esperan", content: "¿Y si vivir para agradar es, en el fondo, una forma elegante de desaparecer?\n\nEmpecé a soltar. De a poco.\n\nA decepcionar con respeto.\n\nA elegir sin justificar.\n\nA desarmar la idea de que ser amado implica cumplir un guion.\n\nNo fue fácil. Ni cómodo. Pero fue necesario.\n\nPorque entendí que no vine a ser la versión perfecta de mí según otros.\n\nVine a ser auténtico, aunque eso signifique incomodar.\n\nY en esa incomodidad... hay libertad." },
  { page: 19, chapter: "Pedir ayuda sin sentir culpa", content: "Siempre me costó pedir ayuda.\n\nNo por orgullo, aunque algo de eso había.\n\nSino porque en algún momento de mi historia aprendí que mostrar necesidad era una forma de debilidad.\n\nY yo quería ser fuerte. Siempre fuerte.\n\nEl que contiene. El que resuelve. El que puede solo.\n\nPero esa fuerza tenía un precio: la soledad.\n\nUna soledad densa, silenciosa, que crecía cada vez que decía \"todo bien\" mientras por dentro me desmoronaba.\n\nMe tomó años entender que pedir ayuda no es rendirse.\n\nEs un acto de humildad, sí. Pero también de confianza.\n\nPorque no se le pide ayuda a cualquiera. Se le pide a quien uno reconoce como refugio, como mano tendida, como presencia real.\n\nAprendí a decir “no puedo”.\n\nA escribir mensajes con la voz temblando.\n\nA dejar que otros me vean frágil, confundido, perdido.\n\nY descubrí que en ese gesto no hay debilidad, hay humanidad.\n\nPedir ayuda es recordarme que no estoy solo.\n\nY que no tengo por qué cargar con todo siempre.\n\nAhora sé que hay días para sostener...\n\ny otros para ser sostenido.\n\nY ambos son igual de válidos." },
  { page: 20, chapter: "Duelo por lo que ya no soy", content: "Hay despedidas que no llevan nombre.\n\nQue no tienen ritual ni aplauso final.\n\nSon las despedidas internas.\n\nEsas donde uno se da cuenta de que ya no encaja en la vida que tiene.\n\nQue algo cambió, aunque todo afuera siga igual.\n\nMe pasó una tarde cualquiera.\n\nMiré alrededor y no reconocí lo que me rodeaba. Las conversaciones, los lugares, incluso mis hábitos... ya no me representaban.\n\nEra como usar ropa que me había quedado chica, pero que seguía poniéndome por costumbre.\n\nAhí supe que tenía que despedirme.\n\nNo de personas. No de objetos.\n\nSino de versiones pasadas de mí.\n\nDel yo que quiso pertenecer.\n\nDel yo que sobrevivió como pudo.\n\nDel yo que se conformó.\n\nY hacer ese duelo fue duro.\n\nPorque aunque esa vida ya no me servía, me había dado sentido durante mucho tiempo. Me había protegido. Me había construido." },
  { page: 21, chapter: "Duelo por lo que ya no soy", content: "Pero dejarla ir era necesario para hacer espacio a lo nuevo. A lo que todavía no sabía cómo sería, pero que ya estaba tocando la puerta.\n\nDuelo no es solo tristeza.\n\nEs también gratitud.\n\nY respeto por lo que fue.\n\nHoy sigo en tránsito.\n\nEntre el pasado que me formó y el futuro que me espera.\n\nPero con una certeza serena: a veces crecer... es dejar morir lo que ya no vibra con lo que soy." },
  { page: 22, chapter: "Reconciliarse con el tiempo perdido", content: "Hay una tristeza particular que no siempre se nombra: la de mirar hacia atrás y sentir que se perdió tiempo.\n\nAños enteros siguiendo caminos que no eran míos.\n\nRelaciones donde me fui apagando.\n\nRutinas vacías.\n\nSueños pospuestos una y otra vez.\n\nY esa pregunta que a veces duele más que cualquier otra:\n\n¿Qué hubiera pasado si...?\n\nDurante mucho tiempo viví en guerra con mi pasado.\n\nMe culpaba por no haber despertado antes, por no haberme escuchado, por haber dicho \"sí\" cuando quería gritar \"no\".\n\nY en esa guerra, el presente también se volvía rehén.\n\nPorque uno no puede construir si se está castigando.\n\nPero un día entendí que no se trata de borrar lo que fue, ni de idealizar lo que pudo ser.\n\nSe trata de reconciliarse.\n\nDe mirar con compasión al que fui." },
  { page: 23, chapter: "Reconciliarse con el tiempo perdido", content: "De entender que hice lo que pude con las herramientas que tenía. Que incluso las decisiones más equivocadas fueron intentos de buscar algo: amor, seguridad, pertenencia.\n\nY en esa comprensión, algo cambió.\n\nEl tiempo perdido dejó de ser pérdida y se volvió lección.\n\nPorque incluso en los años donde no florecí, las raíces crecían.\n\nIncluso en el error, algo aprendí.\n\nY ese aprendizaje, hoy, me hace más humano.\n\nYa no quiero castigarme por lo que no fue.\n\nQuiero usarlo como combustible para lo que puedo llegar a ser." },
  { page: 24, chapter: "La belleza de lo simple", content: "A veces me pasa: me despierto, me hago un café, y por unos minutos... todo está bien.\n\nNo pasa nada extraordinario. No hay revelaciones. Solo una quietud que no grita, pero abraza.\n\nDurante mucho tiempo pensé que la felicidad venía en formato grande.\n\nQue era un premio, una cima, algo que se logra cuando todo encaja.\n\nPero con el tiempo descubrí otra cosa: que la verdadera belleza está en lo simple.\n\nEn una charla sincera.\n\nEn el sol entrando por la ventana.\n\nEn una canción que me hace cerrar los ojos.\n\nEn ese momento en que respiro y me siento presente, sin urgencias.\n\nEl caos, las redes, la cultura del \"más\" nos anestesia. Nos hacen creer que vivir es producir, conquistar, sobresalir.\n\nPero vivir... también es frenar.\n\nTambién es mirar con atención.\n\nTambién es encontrar poesía en lo cotidiano.\n\nHoy me esfuerzo menos por alcanzar lo imposible, y más por valorar lo que ya está.\n\nNo porque me conforme. Sino porque entendí que la plenitud no siempre hace ruido.\n\nA veces se esconde en los pequeños milagros de lo común.\n\nY cuando los veo, algo en mí también se calma." },
  { page: 25, chapter: "Volver a confiar en la vida", content: "Hubo un tiempo en que dejé de confiar.\n\nNo en las personas, necesariamente.\n\nSino en la vida.\n\nSentía que todo era una batalla. Que cada paso implicaba esfuerzo, miedo, incertidumbre.\n\nY que cada vez que algo bueno llegaba, lo hacía con fecha de vencimiento.\n\nAprendí a estar en alerta. A no ilusionarme demasiado. A esperar el golpe detrás de cada alegría.\n\nY en esa tensión... me fui cerrando.\n\nPorque cuando uno deja de confiar, deja también de entregarse.\n\nY vivir con el corazón a medio abrir... es apenas sobrevivir.\n\nPero un día, sin buscarlo, algo se movió.\n\nUn abrazo inesperado.\n\nUna coincidencia que parecía mensaje.\n\nUna sensación de que tal vez, solo tal vez, las cosas pueden salir bien.\n\nY ahí me di cuenta:\n\nVolver a confiar no es ingenuidad.\n\nEs coraje.\n\nEs elegir abrirme al misterio, aún sabiendo que hay riesgo.\n\nEs decirle \"sí\" a la vida, con todo lo que eso implica: el dolor, la belleza, lo inesperado.\n\nLa confianza no es fe ciega. Es una decisión consciente:\n\nseguir caminando, aunque no tenga garantías.\n\nseguir creyendo, aunque no entienda todo.\n\nseguir amando, aunque haya heridas.\n\nY eso... eso también es esperanza." },
  { page: 26, chapter: "El cansancio que no se va con dormir", content: "Hay un tipo de cansancio que no se cura con una siesta ni con vacaciones.\n\nEs un cansancio que vive en los huesos, que pesa en el pecho y no se puede explicar del todo.\n\nUno se despierta después de ocho horas y sigue agotado.\n\nNo es el cuerpo: es el alma.\n\nEs el cansancio de sostener.\n\nDe aparentar.\n\nDe cargar con responsabilidades no dichas.\n\nDe cuidar a todos menos a uno mismo.\n\nDe sentirse detrás, atrasado, como si la vida fuera una carrera en la que nunca se llega.\n\nDurante un tiempo me forcé a seguir igual. A disimular, a empujar.\n\nHasta que un día entendí: no estoy cansado porque hago mucho. Estoy cansado porque me exijo más de lo que puedo dar.\n\nY empecé a observar.\n\n¿En qué momentos me apago?\n\n¿A quién le doy energía sin medida?\n\n¿Qué parte de mí se olvida de sí cuando hay que cumplir?\n\nNo fue fácil aceptar que necesitaba parar.\n\nPero más difícil era seguir fingiendo que podía con todo.\n\nEl descanso real no es solo físico.\n\nEs también emocional.\n\nEs tener espacios donde no hay que rendir, ni demostrar, ni resolver." },
  { page: 27, chapter: "La ternura como forma de resistencia", content: "Hoy me doy permiso.\n\nA veces no rindo igual. A veces no llego.\n\nY está bien.\n\nPorque cuidar mi energía también es una forma de quererme.\n\nVivimos en un mundo rápido, demandante, competitivo.\n\nDonde mostrar emociones parece debilidad.\n\nDonde ser sensible es casi un acto de rebeldía.\n\nY sin embargo, cada vez que alguien me habla con ternura, algo en mí se desarma.\n\nSe afloja.\n\nSe permite.\n\nLa ternura no es sólo dulzura.\n\nEs presencia.\n\nEs mirar al otro sin juzgar.\n\nEs decir: \"estoy acá, te veo, te entiendo\".\n\nY cuando empecé a permitirme ser tierno conmigo, también cambió algo.\n\nYa no necesitaba fingir dureza para protegerme.\n\nPodía llorar sin culpa.\n\nAbrazarme en silencio.\n\nTratarme como trataría a un niño cansado: con paciencia, sin exigencias, con amor.\n\nPorque a veces lo que más necesito no es una solución.\n\nEs un gesto suave.\n\nUn \"no pasa nada\" sincero.\n\nUn recordarme que no tengo que estar bien todo el tiempo.\n\nLa ternura es resistencia.\n\nEn un mundo que te endurece, elegir la suavidad es un acto de valentía.\n\nY cada vez que me abrazo con amabilidad, siento que empiezo a volver." },
  { page: 28, chapter: "Vivir sin sentir", content: "Hubo un tiempo en que me di cuenta de que ya no sentía.\n\nNo tristeza profunda ni alegría verdadera. Nada.\n\nComo si el mundo tuviera el volumen bajado. Como si las emociones estuvieran encerradas detrás de un vidrio grueso, lejanas, inalcanzables.\n\nReía cuando debía reír, decía \"estoy bien\" cuando me preguntaban, pero por dentro... silencio.\n\nY lo peor no era la tristeza: era esa especie de entumecimiento, de vivir en piloto automático, cumpliendo roles, diciendo las frases correctas, asistiendo a los lugares de siempre, sin estar realmente ahí.\n\nMe pregunté si eso era madurar.\n\nSi tal vez la vida adulta consistía en volverse funcional a costa de perder sensibilidad.\n\nPero no era eso.\n\nEra desconexión.\n\nUna defensa. Un mecanismo que el alma activa cuando ya no puede sostener tanto. Cuando las emociones duelen más de lo que se pueden procesar, el sistema se apaga por dentro.\n\nY entendí que no podía forzar sentir.\n\nPero sí podía crear espacio.\n\nDejar de llenarme de ruido. Poner pausa a la sobrecarga. Sentarme, incluso sin ganas, a ver qué aparecía si dejaba de huir.\n\nAl principio no pasó nada.\n\nPero con el tiempo, muy lentamente, empezó a filtrarse la vida. Una canción me hizo llorar. Una charla me hizo reír de verdad. Un olor me recordó quién era. Y ahí supe que estaba volviendo.\n\nDesconectarse no es un fallo. Es un síntoma.\n\nY reconectar, aunque duela, es el acto más valiente.\n\nPorque para volver a sentir, hay que estar dispuesto a abrir la puerta... incluso al dolor.\n\nPero también —y sobre todo— a uno mismo." },
  { page: 29, chapter: "El peso de lo no dicho", content: "Hay silencios que pesan más que cualquier palabra. Son las conversaciones que evitamos, los \"te quiero\" que se quedaron en la garganta, los \"perdón\" que el orgullo silenció. Cargamos con ellos como piedras en los bolsillos, sin darnos cuenta de que nos hunden lentamente. Hablar no siempre alivia, pero callar casi siempre ahoga. A veces, la palabra más difícil de pronunciar es la que nos libera." },
  { page: 30, chapter: "El mapa de tus cicatrices", content: "Nos enseñaron a ocultar las cicatrices, a verlas como imperfecciones. Pero una cicatriz es la prueba de que algo dolió, y también la prueba de que sanó. Son los mapas de nuestras batallas, los recordatorios de nuestra fuerza. No te avergüences de ellas. Una piel sin marcas cuenta una historia incompleta. Tus cicatrices dicen: \"Sobreviví\"." },
  { page: 31, chapter: "La geografía del cuerpo", content: "El cuerpo guarda memorias que la mente olvida. Una tensión en el cuello, un nudo en el estómago, un peso en los hombros. No son malestares al azar. Son el eco de una tristeza no llorada, de un límite no puesto, de un miedo no expresado. Aprender a escuchar tu cuerpo es aprender a leer el lenguaje más honesto de tu alma. Te está diciendo, a su manera, dónde necesitas sanar." },
  { page: 32, chapter: "Rendirse no siempre es perder", content: "Vivimos en una cultura que aplaude la lucha constante, la resistencia a toda costa. Pero hay batallas que no merecen ser peleadas. Hay pesos que no tenemos por qué cargar. A veces, el acto más valiente es soltar la cuerda. Rendirse no a la vida, sino a una versión de la vida que nos está matando. A veces, la única forma de ganar es abandonar la guerra." },
  { page: 33, chapter: "El ruido de los demás", content: "Pasamos tanto tiempo escuchando las opiniones de otros que olvidamos el sonido de nuestra propia voz. Sus \"deberías\", sus \"no puedes\", sus \"eso no es para ti\". Se convierten en un ruido de fondo que, poco a poco, se vuelve nuestra propia melodía. El silencio no es ausencia de sonido. Es el espacio donde, por fin, puedes escucharte a ti mismo. Y esa voz, aunque al principio sea un susurro, es la única que conoce el camino a casa." },
  { page: 34, chapter: "La nostalgia de lo que nunca fue", content: "A veces no extrañamos el pasado que vivimos, sino el que imaginamos que pudimos haber vivido. La decisión no tomada, el amor no intentado, la vida en la otra ciudad. Es una nostalgia peligrosa, porque idealiza lo que no conoce y desprecia lo que sí tiene. Sanar es hacer las paces no solo con lo que pasó, sino también con todo aquello que nunca llegará a pasar. Y entender que tu vida, la real, la presente, también es una posibilidad." },
  { page: 35, chapter: "Habitar la pregunta", content: "Queremos respuestas. Rápidas, claras, definitivas. Pero la vida, a menudo, nos regala preguntas. Preguntas que nos incomodan, que nos desarman, que nos obligan a mirar hacia adentro. No te apresures a responder. A veces, el crecimiento no está en la certeza, sino en la capacidad de habitar la pregunta, de caminar con la incertidumbre, de permitir que la respuesta florezca a su propio ritmo." },
  { page: 36, chapter: "El síndrome del impostor", content: "Ese sentimiento de ser un fraude, de que en cualquier momento alguien descubrirá que no eres tan bueno, tan inteligente, tan capaz. Nace de comparar tu detrás de escena con el escenario principal de los demás. Recuerda: todos están improvisando. Todos sienten miedo. La diferencia es que algunos han aprendido a actuar a pesar de él. No esperes a sentirte seguro para empezar. La seguridad no es un punto de partida, es una consecuencia del camino." },
  { page: 37, chapter: "La belleza de lo imperfecto", content: "Buscamos la perfección como si fuera un destino sagrado. La relación perfecta, el trabajo perfecto, el yo perfecto. Pero la vida no es perfecta. Es rota, es caótica, es maravillosamente imperfecta. Es en las grietas donde entra la luz. Es en las fallas donde reside la humanidad. Amar la vida no es esperar a que todo sea perfecto, es encontrar la belleza en el desorden." },
  { page: 38, chapter: "Estar, no solo parecer", content: "En la era de las pantallas, aprendimos el arte de parecer. Parecer feliz, parecer exitoso, parecer fuerte. Construimos un avatar digital mientras nuestro yo real se desvanece. Pero la conexión auténtica, el amor verdadero, la paz interior... no se encuentran en la apariencia. Se encuentran en la vulnerabilidad de ser. Atrévete a apagar el personaje. Atrévete a estar presente, sin filtros, en tu propia vida." },
  { page: 39, chapter: "Tu propia definición de éxito", content: "Nos vendieron una idea de éxito que tiene que ver con acumular: más dinero, más seguidores, más logros. Pero quizás el éxito es otra cosa. Quizás es tener la valentía de ser tú mismo. Quizás es irte a dormir en paz. Quizás es saber quiénes son tus personas y cuidarlas. Quizás el éxito es construir una vida que se sienta bien por dentro, no una que solo se vea bien por fuera." },
  { page: 40, chapter: "El perdón como un acto egoísta", content: "Perdonar a quien te hirió no es un regalo que le haces. Es un regalo que te haces a ti. Es dejar de cargar con el veneno del rencor. Es liberar espacio en tu alma para cosas nuevas. Perdonar no significa olvidar, ni justificar, ni siquiera reconciliarte. Significa simplemente decir: \"Ya no permitiré que tu herida defina mi presente\". Es un acto de soberanía emocional." },
  { page: 41, chapter: "La valentía de no saber", content: "Creemos que ser fuerte es tener todas las respuestas. Pero a veces, la mayor fortaleza reside en admitir: \"No sé\". No sé qué pasará. No sé cómo hacerlo. No sé cuál es el camino. Esa honestidad nos vuelve humanos, nos abre a aprender, a pedir ayuda, a descubrir posibilidades que la certeza jamás nos mostraría." },
  { page: 42, chapter: "El amor que no necesita ser salvado", content: "Muchas veces amamos desde la carencia, buscando a alguien que nos complete, que nos salve de nosotros mismos. Pero el amor más sano nace del encuentro de dos seres completos. No se trata de encontrar tu media naranja, sino de encontrar otra naranja entera. Un amor que no busca reparar, sino compartir. Que no necesita salvar, sino acompañar." },
  { page: 43, chapter: "Lo que la quietud enseña", content: "Hacemos todo lo posible por evitar la quietud. Llenamos cada segundo con ruido, tareas, distracciones. Porque en la quietud, todo lo que hemos evitado viene a visitarnos. Nuestros miedos, nuestras tristezas, nuestras verdades incómodas. Pero la quietud también es un maestro. Si te quedas el tiempo suficiente, te enseña a respirar, a conocerte, a encontrar una calma que ningún ruido externo puede darte." },
  { page: 44, chapter: "El duelo por las vidas no vividas", content: "En cada elección hay una renuncia. El camino que tomaste implicó dejar otros caminos atrás. Y a veces, duele. Duele pensar en el \"qué hubiera sido si...\". Es un duelo sutil, el duelo por las versiones de ti que nunca existieron. Permítete sentirlo, pero no te quedes a vivir ahí. Honra tus decisiones y camina tu camino, el único que es real, con presencia y gratitud." },
  { page: 45, chapter: "El arte de recibir", content: "Nos enseñan a dar, a ser generosos, a estar para los demás. Pero, ¿sabemos recibir? Un cumplido, un gesto de ayuda, un acto de amor. A menudo nos sentimos incómodos, en deuda, como si no lo mereciéramos. Aprender a recibir es un acto de humildad y de amor propio. Es reconocer que eres digno de cuidado, de afecto, de apoyo. Es permitir que el amor fluya en ambas direcciones." },
  { page: 46, chapter: "La soledad elegida", content: "Hay una soledad que duele, la que nace del abandono o la desconexión. Pero hay otra soledad, una que sana. La soledad elegida. Esos momentos en los que te buscas a ti mismo, en los que disfrutas de tu propia compañía, en los que no necesitas a nadie más para sentirte completo. Esa soledad no es un vacío, es un espacio de libertad. Es el lugar donde te reencuentras." },
  { page: 47, chapter: "Ser amable contigo mismo", content: "Somos nuestro crítico más duro. Nos hablamos con una severidad que jamás usaríamos con un amigo. Nos castigamos por cada error, por cada tropiezo. ¿Y si intentaras ser amable contigo? ¿Si te hablaras con compasión? La autocrítica no te hace mejor, solo te hace sufrir. La amabilidad, en cambio, te da la fuerza para levantarte y volver a intentarlo." },
  { page: 48, chapter: "Las pequeñas alegrías", content: "Esperamos la felicidad en los grandes eventos: el viaje, el ascenso, la boda. Y mientras esperamos, nos perdemos las pequeñas alegrías que salpican cada día. El sabor del primer café de la mañana. Una canción que te recuerda algo bonito. La risa de alguien que quieres. La felicidad no es un destino. Es la capacidad de reconocer la magia en los momentos ordinarios." },
  { page: 49, chapter: "Los finales necesarios", content: "Nos aferramos a lo conocido, aunque nos haga daño. Un trabajo, una relación, una amistad. Nos da pánico el vacío que podría dejar un final. Pero hay cosas que necesitan terminar para que algo nuevo pueda nacer. Soltar no es fracasar. Es hacer espacio. Es entender que algunos finales no son una pérdida, son una liberación." },
  { page: 50, chapter: "El cuerpo como hogar", content: "Pasamos la vida habitando un cuerpo que a menudo tratamos como a un enemigo. Lo criticamos, lo castigamos, lo ignoramos. ¿Y si empezaras a verlo como tu hogar? El único que tienes. Un hogar que necesita cuidado, respeto, nutrición. Hacer las paces con tu cuerpo es hacer las paces con tu existencia. Es empezar a sentirte, por fin, en casa." },
  { page: 51, chapter: "La intuición como brújula", content: "La mente analiza, duda, calcula. Pero hay otra forma de sabiduría dentro de ti: la intuición. Esa corazonada, esa sensación en el estómago, ese \"algo me dice que...\". Hemos aprendido a desconfiar de ella, a priorizar la lógica. Pero la intuición es la brújula del alma. No siempre te dará el porqué, pero siempre te señalará la dirección correcta. Aprende a escucharla." },
  { page: 52, chapter: "Celebrar el proceso", content: "Nos obsesionamos con la meta, con llegar. Y nos olvidamos de celebrar el proceso. Cada pequeño paso, cada lección aprendida, cada vez que te levantaste después de caer. El valor no está solo en la cima de la montaña, sino en cada paso de la escalada. No esperes a llegar para sentirte orgulloso. El camino también es el destino." },
  { page: 53, chapter: "La vulnerabilidad como fuerza", content: "Nos enseñaron que ser vulnerable es ser débil. Que hay que mostrarse fuerte, invencible. Pero la verdadera fuerza reside en la capacidad de mostrar tus heridas, de decir \"tengo miedo\", de admitir \"necesito ayuda\". La vulnerabilidad no te aleja de los demás, te conecta. Es el puente que permite el paso al amor, a la empatía, a la conexión real." },
];

/**
 * Fix: Exported getGenAI function for LiveJournal component.
 * Returns the shared client instance ensuring the API key is configured.
 */
export function getGenAI() {
    return ensureClient();
}

/**
 * Fix: Exported generateBookContent function for App component.
 * It returns the hardcoded book content as a resolved promise.
 */
export const generateBookContent = async (): Promise<Page[]> => {
    return Promise.resolve(FULL_BOOK);
};

/**
 * Fix: Exported summarizeText function for EbookReader component.
 * Uses Gemini to generate a short summary of the provided text.
 */
export const summarizeText = async (text: string): Promise<string> => {
    const client = ensureClient();
    const response = await client.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: `Resume el siguiente texto en una o dos frases, capturando la idea principal:\n\n"${text}"`,
    });
    return response.text;
};

const bookContext = FULL_BOOK.map(p => `Página ${p.page}, Capítulo: ${p.chapter}\n${p.content}`).join('\n\n');

/**
 * Fix: Exported getChatbotResponse function for Chatbot component.
 * Creates a chat session with history and system instructions to provide context-aware responses.
 */
export const getChatbotResponse = async (history: Content[], message: string): Promise<string> => {
    const client = ensureClient();
    const chat = client.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            systemInstruction: `Eres un guía de reflexión basado en el libro 'A VECES CAER, A VECES VOLAR' de Cristofer Brañas. Tu propósito es ayudar a los usuarios a profundizar en los conceptos del libro. El contenido del libro es el siguiente:\n\n${bookContext}\n\nResponde de forma concisa y útil.`
        },
        history: history,
    });

    const result = await chat.sendMessage({ message: message });
    return result.text;
};

/**
 * Fix: Exported getGroundedResponse for ResearchAssistant component.
 * Uses Google Search grounding to provide up-to-date answers and returns sources.
 */
export const getGroundedResponse = async (query: string): Promise<{ text: string; chunks: GroundingChunk[] }> => {
    const client = ensureClient();
    const response = await client.models.generateContent({
        model: "gemini-2.5-flash",
        contents: query,
        config: {
            tools: [{googleSearch: {}}],
        },
    });

    const text = response.text;
    const groundingMetadata = response.candidates?.[0]?.groundingMetadata;
    
    const chunks: GroundingChunk[] = groundingMetadata?.groundingChunks
        ?.map(c => c.web ? { web: { uri: c.web.uri, title: c.web.title } } : null)
        .filter((c): c is GroundingChunk => c !== null) || [];
    
    return { text, chunks };
}

/**
 * Fix: Exported editImage for ImageEditor component.
 * Uses a multimodal model to edit an image based on a text prompt.
 */
export const editImage = async (base64String: string, mimeType: string, prompt: string): Promise<string> => {
    const client = ensureClient();
    const response = await client.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { inlineData: { data: base64String, mimeType: mimeType } },
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated.");
};

/**
 * Fix: Exported generateInstagramPostImage for InstaPostCreator component.
 * Generates an image from a text prompt with specific styling instructions.
 */
export const generateInstagramPostImage = async (text: string): Promise<string> => {
    const prompt = `Crea una imagen para una publicación de Instagram, con ratio 1:1. La imagen debe tener un fondo de papel texturizado de color crema o blanco roto. Sobre este fondo, muestra el siguiente texto con una fuente que imite una máquina de escribir clásica (como Courier), en color negro. El texto debe estar centrado y presentado de forma estética, como una cita o un poema corto. No incluyas ningún otro elemento gráfico, solo el texto y el fondo de papel. Al final del texto, en la esquina inferior derecha, añade la firma "arizzta frases" en un tamaño más pequeño y con un estilo de letra manuscrita, ligeramente difuminado, como si estuviera escrito con tinta. El texto principal es: "${text}"`;

    const client = ensureClient();
    const response = await client.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [{ text: prompt }],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }
    
    throw new Error("No image was generated for the post.");
};
